### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by hmcy** [twoone-3/BDSpyrunner#1]
没有编译成dll吗？可以编译成dll发布出来吗？谢谢
是不是用了这个插件之后就可以用Python来开发插件？

**Comment by jfishing** [comment]
等完成后，就可以使用python开发插件了，目前Towone还在开发中，敬请期待

**Comment by hmcy** [comment]
好的，期待中

**Comment by jfishing** [comment]
发布了内测版，有兴趣可以体验一下

**Comment by hmcy** [comment]
[http://1798.ink/20200928.png](url)
这是怎么回事

**Comment by hmcy** [comment]
![微信截图_20200928111337](https://user-images.githubusercontent.com/31857328/94387273-43cccd80-017c-11eb-8226-84879df141ee.png)

**Comment by hmcy** [comment]
无法定位程序输入点GetServerSymbol于动态链接库

**Comment by hmcy** [comment]
![Uploading 微信截图_20200928111337.png…]()

**Comment by jfishing** [comment]
请升级一下bdxcore

**Comment by hmcy** [comment]
用的是0721是最新版本了啊

**Comment by hmcy** [comment]
噢，可以运行了

**Comment by hmcy** [comment]
请问有示列插件可以参考吗？

**Comment by hmcy** [comment]
可以增加一个热加载功能吗？每次修改都要重新启动服务器，要是可以输入一个指令就重新加载PY文件就好了

**Comment by jfishing** [comment]
好的，下载版本加
