### ISSUE TITLE
PYR1.9.5的某个API存在严重级别的内存泄漏 ！！！

### ISSUE THREAD

**Issue by crowforkotlin** [twoone-3/BDSpyrunner#25]
getPlatyerList的泄漏速度将近 200MB / s

代码如下
`import threading
import mc

def startThread(data):
    threading.Thread(target=test).start()

def test():
    while (True):
        playerList = mc.getPlayerList()

mc.setListener('onJoin', startThread)
`

**Comment by crowforkotlin** [comment]
![image](https://user-images.githubusercontent.com/60876546/152216138-f18a5b44-1357-4db0-a560-68687349aa61.png)
可以看看LXL的获取方法

**Comment by twoone-3** [comment]
已修复
