### ISSUE TITLE
Eror 127

### ISSUE THREAD

**Issue by dm-vev** [twoone-3/BDSpyrunner#27]
20:06:26 ERROR [LiteLoader] Fail to load plugin <BDSpyrunner.dll>
20:06:26 ERROR [LiteLoader] Error: Code[127] The specified procedure could not be found.

python 3.7.9 installed

**Comment by dm-vev** [comment]
note: this python is the only one in the system

**Comment by twoone-3** [comment]
maybe you have not do as the guidance
