### ISSUE TITLE
[求助] 如何引入外部库

### ISSUE THREAD

**Issue by CJYKK** [twoone-3/BDSpyrunner#28]
我想引入apscheduler.schedulers.background库，已经使用pip安装完成，原版Python也可以import
但在BDSpyrunner里却提示
`ERROR [BDSpyrunner] ModuleNotFoundError: No module named 'apscheduler'`

**Comment by twoone-3** [comment]
```py
import sys
print(sys.path)
```
尝试修改sys.path

**Comment by VincentX0905** [comment]
> ```python
> import sys
> print(sys.path)
> ```
> 
> 嘗試修改sys.path

can you create a docs to explain this?

**Comment by twoone-3** [comment]
OK, but normally, the site-package folder should be automatically found and added to path. I can wait for the 2.0.0 version

**Comment by VincentX0905** [comment]
not at all
i don't know why
i have tested aiohttp websockets discord
Can not...
![image](https://user-images.githubusercontent.com/76867533/176593484-49d652ec-22f9-44ff-9628-ff9c464f3e88.png)
![image](https://user-images.githubusercontent.com/76867533/176593517-17d00290-847f-4b33-80c5-9f97b96118a9.png)

**Comment by twoone-3** [comment]
print(sys.path) and find out the pip install folder.

**Comment by VincentX0905** [comment]
![image](https://user-images.githubusercontent.com/76867533/176594788-b92aba13-c169-4498-b88d-b684d74d4fa6.png)

**Comment by twoone-3** [comment]
It seems like the pip folder is in your path, open the site-packages folder and check whether the WS is in the foler.
I guess the folder is empty...

**Comment by VincentX0905** [comment]
no
![image](https://user-images.githubusercontent.com/76867533/176604722-38c74aa9-272b-4ee9-9cf0-38c0e8aa8da1.png)

**Comment by twoone-3** [comment]
maybe you wound print(sys.path) in .py plugin

**Comment by VincentX0905** [comment]
I really don't have a clue...
![image](https://user-images.githubusercontent.com/76867533/176605518-baccd05b-9ada-46fd-8005-62d8a9483973.png)

**Comment by twoone-3** [comment]
well don't chose the text, I can't see it clearly
Look! the sys.path have not the site-package folder, so you should add it by hand

**Comment by VincentX0905** [comment]
i didn't chose the text
it auto set text background

and how to set it to load `site-package` folder?

**Comment by twoone-3** [comment]
sys.path 是一个list ，所以你应该把site-package的绝对路径加入sys.apth，记得要写在插件里

**Comment by VincentX0905** [comment]
but i don't know how to add file path to the plugins...
have any example?

**Comment by twoone-3** [comment]
append
