### ISSUE TITLE
getAllItem & setAllItem方法存在部分nbt无法正常使用的情况

### ISSUE THREAD

**Issue by disymayufei** [twoone-3/BDSpyrunner#3]
如烟花的颜色nbt，在getAllItem后不会正常显示，同时即使手动添加"FireworkColor1" : 0这一项，在执行setAllItem后，烟花依然是颜色标签丢失的状态，这给备份玩家背包和给予玩家指定颜色的烟花带来了一定困难，望作者大大修复

**Comment by twoone-3** [comment]
已收到

**Comment by twoone-3** [comment]
已修复
