### ISSUE TITLE
Error 126 can not found lib

### ISSUE THREAD

**Issue by VincentX0905** [twoone-3/BDSpyrunner#30]
if i just install the plugin
**look:**
![image](https://user-images.githubusercontent.com/76867533/176688330-cb5a0d0f-aa10-4307-94dd-9a058c52b639.png)

**console show this:`(Fail to load plugin <BDSpyrunner.dll>)`**
![image](https://user-images.githubusercontent.com/76867533/176688700-9feed468-6594-4908-a90d-b7fdfde7a1dc.png)

**python version:(3.7.9)**
![image](https://user-images.githubusercontent.com/76867533/176697625-c2c9f243-ced4-4a52-ae22-e4e32d4761a5.png)

**Comment by VincentX0905** [comment]
![image](https://user-images.githubusercontent.com/76867533/176697744-16aab357-3ffe-4414-af96-393b1929b8fb.png)

**Comment by twoone-3** [comment]
老版本确实有问题，请等待新版本发布

**Comment by VincentX0905** [comment]
and now have any method to fix this?

**Comment by VincentX0905** [comment]
then can you support to python3.7.13 or 3.8 3.9 3.10 etc...
python3.7.9 Installation is inconvenient

**Comment by twoone-3** [comment]
3.7.13 没有安装包，更高的版本可能有不兼容的问题，我不敢随意更改
