### ISSUE TITLE
BDSpyrunner error on 1.19.51

### ISSUE THREAD

**Issue by mandong1240** [twoone-3/BDSpyrunner#39]
[TrackBack_20230111_00-54-24.log](https://github.com/twoone-3/BDSpyrunner/files/10384494/TrackBack_20230111_00-54-24.log)

[TrackBack] Function BDS_Main::_hook at 0x7FFAB6E5B870  [BDSpyrunner.dll]
-- At File D:\a\BDSpyrunner\BDSpyrunner\mod.cpp : Line 317 

Fix please.

**Comment by twoone-3** [comment]
please let me know your liteloader version

**Comment by mandong1240** [comment]
LiteLoaderBDS 2.9.0

**Comment by twoone-3** [comment]
I have tested in my device, ll290 bds 1.19.51 no problem
