### ISSUE TITLE
[建议]新增api

### ISSUE THREAD

**Issue by Hato626** [twoone-3/BDSpyrunner#5]
新增爆炸函数 栗子: setExplore(pos.x, pos.y, pos.z, dim , Explosive power[int], Explosive range[int] , Fire[bool])
这个函数既然有了监听, 建议增加调用

**Comment by twoone-3** [comment]
你有试过吗

**Comment by Hato626** [comment]
> 你有试过吗

在1.16.02的时候试过， 之后版本就没试过了

**Comment by Hato626** [comment]
> 你有试过吗

![image](https://user-images.githubusercontent.com/63497854/116891575-746c6c80-ac61-11eb-841a-1ec7b3f5a1ab.png)

这里是当时留的笔记, 这个函数应该是在 level::explore上吧

**Comment by Hato626** [comment]
希望pyrunner的api能 摩多摩多
这里还有几个希望加入的api

调用函数 :
1. 改变实体大小函数 ,栗子 setSize(Actor*, float, float)
- 已知: 此函数在 actor::setSize 中,有三个参数 第一个参数为实体指针 第二第三个不清楚(为控制长宽或高)
- 返回值不知
- 此函数可用 因为minebbs有个国外开发者曾经用过此函数做出了插件

2.骑乘实体 ,栗子 addRide(Actor1* , Actor2*)
- 已知: 此函数在 actor::addride中 , 两个指针为被骑实体和 骑乘实体 
- note : 这里这个函数不会标记实体在骑乘状态 ，所以当在游戏里按shift 表面停止骑乘 实际还在骑乘
- 返回值为bool值

可能有用的有关函数 :
```
actor::isRider 
参数 (actor1* actor2*) 
作用 检测该实体是否是骑乘状态 
返回值 bool 
备注 前一参数为被骑生物,后一参数为骑乘的生物
```
```
actor::canAddRider
参数 (Actor1* Actor2*)
作用 检测能否骑乘 （因为有些生物背上有东西骑不上去）
返回值 bool
备注 前一参数为被骑生物,后一参数为骑乘的生物
```
```
actor::getRide
参数 (Actor*)
作用 检测该生物骑乘的生物 
返回值 Actor* (为被骑乘生物)
备注 参数为骑乘生物
```

3.是否潜行, 栗子 isSneaking(actor*)
- 已知： 此函数在 Actor::isSneaking 中 
- 返回值 bool

监听函数 :

1. 监听末影人随机瞬移 ,栗子 onEndermanRandomTeleport()
```
此函数在 TeleportComponent::randomTeleport
可拦截
回传参数 实体指针
```

**Comment by twoone-3** [comment]
收到

**Comment by twoone-3** [comment]
Entity加入SetSize功能，参数两个float，Entity加入属性issneacking，用于查询是否潜行，
已经增加了这两个

**Comment by Hato626** [comment]
太好了 setSize ...能做不少有趣的插件呢

**Comment by Hato626** [comment]
那我这个issue就关了

**Comment by ghost** [comment]
建议增加bossbar的多行设置，而不是仅仅是单行

**Comment by twoone-3** [comment]
> 建议增加bossbar的多行设置，而不是仅仅是单行

OK

**Comment by twoone-3** [comment]
> 建议增加bossbar的多行设置，而不是仅仅是单行

研究了一下，似乎需要用到uniqueId，但是因为不能凭空产生，所以不能设置多行

**Comment by twoone-3** [comment]
> 希望pyrunner的api能 摩多摩多
> 这里还有几个希望加入的api
> 
> 调用函数 :
> 
> 1. 改变实体大小函数 ,栗子 setSize(Actor*, float, float)
> 
> * 已知: 此函数在 actor::setSize 中,有三个参数 第一个参数为实体指针 第二第三个不清楚(为控制长宽或高)
> * 返回值不知
> * 此函数可用 因为minebbs有个国外开发者曾经用过此函数做出了插件
> 
> 2.骑乘实体 ,栗子 addRide(Actor1* , Actor2*)
> 
> * 已知: 此函数在 actor::addride中 , 两个指针为被骑实体和 骑乘实体
> * note : 这里这个函数不会标记实体在骑乘状态 ，所以当在游戏里按shift 表面停止骑乘 实际还在骑乘
> * 返回值为bool值
> 
> 可能有用的有关函数 :
> 
> ```
> actor::isRider 
> 参数 (actor1* actor2*) 
> 作用 检测该实体是否是骑乘状态 
> 返回值 bool 
> 备注 前一参数为被骑生物,后一参数为骑乘的生物
> ```
> 
> ```
> actor::canAddRider
> 参数 (Actor1* Actor2*)
> 作用 检测能否骑乘 （因为有些生物背上有东西骑不上去）
> 返回值 bool
> 备注 前一参数为被骑生物,后一参数为骑乘的生物
> ```
> 
> ```
> actor::getRide
> 参数 (Actor*)
> 作用 检测该生物骑乘的生物 
> 返回值 Actor* (为被骑乘生物)
> 备注 参数为骑乘生物
> ```
> 
> 3.是否潜行, 栗子 isSneaking(actor*)
> 
> * 已知： 此函数在 Actor::isSneaking 中
> * 返回值 bool
> 
> 监听函数 :
> 
> 1. 监听末影人随机瞬移 ,栗子 onEndermanRandomTeleport()
> 
> ```
> 此函数在 TeleportComponent::randomTeleport
> 可拦截
> 回传参数 实体指针
> ```

addRider似乎并没有什么用，所以我不想费心思去研究了，时间宝贵
