### ISSUE TITLE
[建议]将设置指令说明api更改为注册指令api

### ISSUE THREAD

**Issue by Aleksanaa** [twoone-3/BDSpyrunner#9]
如题。如果只设置指令说明的话，使用时会提示未知指令，影响游戏体验。
LiteLoader提供了[指令注册api](https://docs.litetitle.com/#/zh_cn/LL/PluginsDev/Register-Commands?id=%e6%b3%a8%e5%86%8c%e6%8c%87%e4%bb%a4)，可否至少在插件被LiteLoader加载时提供指令注册api？
（题外话，pyr并不支持最新版bdxcore和支持liteloader(<1.0.3)两点应该在wiki说明的）

**Comment by twoone-3** [comment]
注册也一样吧，而且支持不支持我并不知道
